### ISSUE TITLE
Error: %1 is not a valid Win32 application. (Win 8)

### ISSUE THREAD

**Issue by Ivanca** [rc0x03/node-libxmljs-dom#1]
Windows.js calls `require("js-beautify")` despite not being a dependency, naturally it throws an error:

```
Error: Cannot find module 'js-beautify'
```

But even after fixing this issue by installing it manually, another issue appears, which I haven't resolved:

```
Error: %1 is not a valid Win32 application.
\\?\C:\XXX\node_modules\libxmljs\build\Release\xmljs.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (C:\XXX\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\XXX\node_modules\libxmljs\lib\bindings.js:1:99)

    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

Using latest npm, latest NodeJS on Windows 8.1

One workaround is to use Osmosis 0.0.8 instead of 0.0.9

**Comment by rc0x03** [comment]
This should be fixed in the latest GitHub version
